#!/bin/bash

PICOPATH=/pico

# Transpile the CoffeeScript files
echo "Transpiling Coffeescript"
coffee -c -o $PICOPATH/web/js/ $PICOPATH/web/coffee/

# Shutdown the server
echo "Shutting down nginx"
sudo service nginx stop

# Clean out the old files
echo "Cleaning up old files"
sudo rm -rf /srv/http/ctf/*

echo "Generating web with Jekyll"
cd $PICOPATH/web
sudo jekyll build

echo "Copying files to server"
#sudo cp -r /home/vagrant/web/* /srv/http/ctf/
mkdir -p $PICOPATH/problem_static
sudo cp -r $PICOPATH/problem_static /srv/http/ctf/problem-static

# Make sure everything is in UNIX format.
sudo dos2unix -q /srv/http/ctf/*.html

# Start the server
echo "Restarting the server"
sudo service nginx start

# Clear the cache
echo "Clearing the API cache"
$PICOPATH/api/api_manager.py database clear cache

#Start picoCTF API
echo "Starting the picoCTF API"
tmux kill-session -t picoapi 2> /dev/null
killall gunicorn
#tmux new-session -s picoapi -d "cd $PICOPATH/api && python3 run.py"
cd $PICOPATH/api && ./gunicorn_start.sh &
